### ISSUE TITLE
Number of channels in cv2.StereoSGBM_create

### ISSUE THREAD

**Issue by vini-c-costa** [FoamoftheSea/KITTI_visual_odometry#2]
Hi,

First of all, congratulations! It's probably the best explanation of Visual Odommetry in the entire internet.

In your application, you used cv2.StereoSGBM_create and included that variables:

```
matcher = cv2.StereoSGBM_create(numDisparities=num_disparities,
                                    minDisparity=0,
                                    blockSize=block_size,
                                    P1 = 8 * 3 * sad_window ** 2,
                                    P2 = 32 * 3 * sad_window ** 2,
                                    mode=cv2.STEREO_SGBM_MODE_SGBM_3WAY
                                   )
```

But seeing the documentation in opencv website, it seems that:

```
P1 and P2 should be multiplied by 8*number_of_image_channels*blockSize*blockSize and 32*number_of_image_channels*blockSize*blockSize , respectively. And in your code, the images that you've used in the examples has just one channel, which means that the operation is a bit different when compared to the recommendation.
```

It's just a suggestion to improve your work, and I hope you see that issue with good eyes.

Again, thank you for what you've been doing. Great job!

**Comment by FoamoftheSea** [comment]
Hi @vini-cc, thank you for the kind words! I am really glad so many people have found this tutorial useful 😊

This is a good catch and thanks for pointing it out. IIRC I either ended up with better results using 3 here even though the images are single channel, and didn't want to confuse the reader so I didn't mention it, but you are absolutely correct! It would be good to repeat the experiment with the correct value again to double check if the results would not improve.
