### ISSUE TITLE
os.listdir does not list the name of the images in ascending order

### ISSUE THREAD

**Issue by ananyaverma2** [FoamoftheSea/KITTI_visual_odometry#3]
In the Dataset_handler class, the os.listdir lists the names of the images arbitrarily, which causes the function match_features to not give accurate results as the image 000000.png (self.first_image_left) is not being compared to 000001.png (self.second_image_left) but rather another arbitrary image.

```
self.left_image_files = os.listdir(self.seq_dir + 'image_0')
self.right_image_files = os.listdir(self.seq_dir + 'image_1')
self.velodyne_files = os.listdir(self.seq_dir + 'velodyne')
```

This can be solved by sorting the names of the images generated as shown below

```
self.left_image_files.sort()
self.right_image_files.sort()
self.velodyne_files.sort()
```

**Comment by FoamoftheSea** [comment]
Thank you for flagging this. The issue has been fixed in https://github.com/FoamoftheSea/KITTI_visual_odometry/pull/4
